# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_server_server_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=128, unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后修改时间'),
        ),
    ]
